library(dplyr)
library(tidyr)
DIR<-getwd()

names<-c("ALFL","AMCR","AMGO","AMRE","AMRO",
         "ATTW","BANS","BAOR","BARS","BAWW",
         "BBMA","BBWA","BBWO","BCCH","BEKI",
         "BHVI","BLBW","BLJA","BLPW","BOCH","CAWA",
         "CEDW","CHSP","CMWA","CONW","COYE","DEJU",
         "EAPH","EVGR","GCKI","GRAJ","GRYE","HAWO",
         "HETH","LCSP","LEFL","LISP","MAWA","MOWA",
         "NOFL","OSFL","OVEN","PAWA","PHVI","PIGR","PISI",
         "PIWO","PUFI","RBGR","RBNU","RCKI","RECR",
         "REVI","RUBL","RUGR","SWTH","TEWA","TRES",
         "WAVI","WTSP","WETA","WEWP","WIWA","WIWR",
         "WISN","WWCR","YBSA","YEWA","YRWA","YBFL") 

#get preferred habitat for each species: ideally if value of a particular habitat was 0 we 
#wouldn't add it to the indicator
for (SPP in names){
  pref.hab<-read.csv("preferred habitat indicators/ssh-north.csv")
  pref.hab.spp<-pref.hab[pref.hab$X==SPP,]
  spp.prefs<-print(paste0("moving_window(input=",
               ifelse(pref.hab.spp$Mixedwood==1,
                      "if(indicator(name='Mixed Age AVI', units='absolute')<60,indicator(name='Mixed AVI unity ac_new', units='density'),0)",
                      ""),
               "+",
               ifelse(pref.hab.spp$MixedwoodO==1,
                      "if(indicator(name='Mixed Age AVI', units='absolute')>60,indicator(name='Mixed AVI unity ac_new', units='density'),0)",
                      ""),
               "+",
               ifelse(pref.hab.spp$BSpr==1,
                      "if(indicator(name='Black Spruce Age AVI', units='absolute')<80,indicator(name='Black Spruce AVI unity ac_new', units='density'),0)",
                      ""),
               "+",
               ifelse(pref.hab.spp$BSprO==1,
                      "if(indicator(name='Black Spruce Age AVI', units='absolute')>80,indicator(name='Black Spruce AVI unity ac_new', units='density'),0)",
                      ""),
               "+",
               ifelse(pref.hab.spp$Spruce==1,
                      "if(indicator(name='White Spruce Age AVI', units='absolute')<80,indicator(name='White Spruce AVI unity ac_new', units='density'),0)",
                      ""),
               "+",
               ifelse(pref.hab.spp$SpruceO==1,
                      "if(indicator(name='White Spruce Age AVI', units='absolute')>80,indicator(name='White Spruce AVI unity ac_new', units='density'),0)",
                      ""),
               "+",
               ifelse(pref.hab.spp$Pine==1,
                      "if(indicator(name='Pine Age AVI', units='absolute')<80,indicator(name='Pine AVI unity ac_new', units='density'),0)",
                      ""),
               "+",
               ifelse(pref.hab.spp$PineO==1,
                      "if(indicator(name='Pine Age AVI', units='absolute')>80,indicator(name='Pine AVI unity ac_new', units='density'),0)",
                      ""),
               "+",               
               ifelse(pref.hab.spp$Larch==1,
                      "if(indicator(name='Larch Age AVI', units='absolute')<80,indicator(name='Larch AVI unity ac_new', units='density'),0)",
                      ""),
               "+",
               ifelse(pref.hab.spp$LarchO==1,
                      "if(indicator(name='Larch Age AVI', units='absolute')>80,indicator(name='Larch AVI unity ac_new', units='density'),0)",
                      ""),
               "+", 
               ifelse(pref.hab.spp$Decid==1,
                      "if(indicator(name='Deciduous Age AVI', units='absolute')<80,indicator(name='Deciduous AVI unity ac_new', units='density'),0)",
                      ""),
               "+",
               ifelse(pref.hab.spp$DecidO==1,
                      "if(indicator(name='Deciduous Age AVI', units='absolute')>80,indicator(name='Deciduous AVI unity ac_new', units='density'),0)",
                      ""),
               "+", 
               ifelse(pref.hab.spp$Swamp==1,
                      "indicator(name='Wetlands Swamp', units='density')",
                      ""),
               "+", 
               ifelse(pref.hab.spp$Shrub==1,
                      "indicator(name='Shrubland', units='density')",
                      ""),
               "+", 
               ifelse(pref.hab.spp$GraminoidFen==1,
                      "indicator(name='Wetlands Fen', units='density')",
                      ""),
               "+", 
               ifelse(pref.hab.spp$Marsh==1,
                      "indicator(name='Wetlands Marsh', units='density')",
                      ""),
               "+", 
               ifelse(pref.hab.spp$GrassHerb==1,
                      "indicator(name='Grassland', units='density')",
                      ""),
               "+", 
               ifelse(pref.hab.spp$Crop==1,
                      "indicator(name='Agriculture Crops Unityb', units='density')",
                      ""),
               "+", 
               ifelse(pref.hab.spp$RoughP==1,
                      "indicator(name='Agriculture Pasture Unityb', units='density')",
                      ""),
               "+", 
               ifelse(pref.hab.spp$Urban==1,
                      "indicator(name='Urban Undifferentiated Unityb', units='density')",
                      ""),
               "+", 
               ifelse(pref.hab.spp$Rural==1,
                      "indicator(name='Rural Acreage Undifferentiated', units='density')",
                      ""),
               "+", 
               ifelse(pref.hab.spp$Industrial==1,
                      "indicator(name='Industrial Undifferentiated Unityb', units='density')",
                      ""),
               "+", 
               ifelse(pref.hab.spp$Mine==1,
                      "indicator(name='Mine Pits Unityb', units='density')",
                      ""),
               "+", 
               ", radius=1000, method='mean')"))
  capture.output(spp.prefs, file=paste0("preferred habitat indicators/",SPP,"indicator.habitatprefs.txt"))
  
}#Note: look for and delete any multiple consecutive "+" signs from indicator formula before entering into
#ALCES Advanced Calculator.

#create the indicator for each species
for (SPP in names){
  #read in model coefficients file
  spp.coef=read.csv(paste0(DIR,"/model coefficients/",SPP,".HFmodelcoefficients.csv"))
  #get summary of model coefficient runs 
  med.coef<-spp.coef%>%
    summarise(Intercept=median(X.Intercept.),
              vegcBSpr=median(vegcBSpr),
              vegcCrop=median(vegcCrop),
              vegcGraminoidFen=median(vegcGraminoidFen),
              vegcGrassHerb=median(vegcGrassHerb),
              vegcIndustrial=median(vegcIndustrial),
              vegcLarch=median(vegcLarch),
              vegcMarsh=median(vegcMarsh),
              vegcMine=median(vegcMine),
              vegcMixedwood=median(vegcMixedwood),
              vegcPine=median(vegcPine),
              vegcRoughP=median(vegcRoughP),
              vegcRural=median(vegcRural),
              vegcShrub=median(vegcShrub),
              vegcSpruce=median(vegcSpruce),
              vegcSwamp=median(vegcSwamp),
              vegcTameP=median(vegcTameP),
              vegcUrban=median(vegcUrban),
              wtAge=median(wtAge),
              wtAge2=median(wtAge2),
              wtAge05=median(wtAge05),
              fCC2=median(fCC2),
              ROAD=median(ROAD),
              mWell=median(mWell),
              mSoft=median(mSoft),
              mEnSft=median(mEnSft),
              mTrSft=median(mTrSft),
              mSeism=median(mSeism),
              CMETHODSM=median(CMETHODSM),
              CMETHODRF=median(CMETHODRF),
              pWater_KM=median(pWater_KM),
              pWater2_KM=median(pWater2_KM),
              xPET=median(xPET),xMAT=median(xMAT),xAHM=median(xAHM),xFFP=median(xFFP),
              xMAP=median(xMAP),xMWMT=median(xMWMT),xMCMT=median(xMCMT),
              xMAP.xPET=median(xMAP.xPET),xAHM.xMAT=median(xAHM.xMAT),xFFP.xMAP=median(xFFP.xMAP),
              xY=median(xY),xX=median(xX),xY2=median(xY2),xX2=median(xX2),xX.xY=median(xX.xY),
              SSH_KM=median(SSH_KM),SSH05_KM=median(SSH05_KM),
              Cult_KM=median(Cult_KM),THF_KM=median(THF_KM),Lin_KM=median(Lin_KM),Nonlin_KM=median(Nonlin_KM),
              Succ_KM=median(Succ_KM),Alien_KM=median(Alien_KM),Noncult_KM=median(Noncult_KM),
              THF2_KM=median(THF2_KM),Nonlin2_KM=median(Nonlin2_KM),Succ2_KM=median(Succ2_KM),
              Alien2_KM=median(Alien2_KM),Noncult2_KM=median(Noncult2_KM),
              isBSLarch.wtAge=median(isBSLarch.wtAge),
              isBSLarch.wtAge2=median(isBSLarch.wtAge2),
              isBSLarch.wtAge05=median(isBSLarch.wtAge05),
              isMix.wtAge=median(isMix.wtAge),
              isMix.wtAge2=median(isMix.wtAge2),
              isMix.wtAge05=median(isMix.wtAge05),
              isPine.wtAge=median(isPine.wtAge),
              isPine.wtAge2=median(isPine.wtAge2),
              isPine.wtAge05=median(isPine.wtAge05),
              isWSpruce.wtAge=median(isWSpruce.wtAge),
              isWSpruce.wtAge2=median(isWSpruce.wtAge2),
              isWSpruce.wtAge05=median(isWSpruce.wtAge05),
              isUpCon.wtAge=median(isUpCon.wtAge),
              isUpCon.wtAge2=median(isUpCon.wtAge2),
              isUpCon.wtAge05=median(isUpCon.wtAge05),
              isCon.wtAge=median(isCon.wtAge),
              isCon.wtAge2=median(isCon.wtAge2),
              isCon.wtAge05=median(isCon.wtAge05))
  #print script
  spp.script<-print(paste0("(",med.coef$Intercept,"+
                           if(indicator(name='Black Spruce AVI unity ac_new', units='density', nodata_fill=0)>50, ",
                           med.coef$vegcBSpr,
                           ",if(indicator(name='Deciduous AVI unity ac_new', units='density', nodata_fill=0)>50,0,
                           if(indicator(name='Agriculture Crops Unityb', units='density', nodata_fill=0)>50, ",
                           med.coef$vegcCrop,
                           ",if(indicator(name='Wetlands Fen', units='density', nodata_fill=0)>50, ",
                           med.coef$vegcGraminoidFen,
                           ", if(indicator(name='Grassland Unityb', units='density', nodata_fill=0)>50, ",
                           med.coef$vegcGrassHerb,
                           ",if(indicator(name='Industrial Undifferentiated Unityb', units='density', nodata_fill=0)>50, ",
                           med.coef$vegcIndustrial,
                           ",if(indicator(name='Larch AVI unity ac_new', units='density', nodata_fill=0)>50, ",
                           med.coef$vegcLarch,
                           ",if(indicator(name='Wetlands Marsh', units='density', nodata_fill=0)>50, ",
                           med.coef$vegcMarsh,
                           ",if(indicator(name='Mine Pits Unityb', units='density', nodata_fill=0)>50, ",
                           med.coef$vegcMine,
                           ",if(indicator(name='Mixed AVI unity ac_new', units='density', nodata_fill=0)>50, ",
                           med.coef$vegcMixedwood,
                           ",if(indicator(name='Pine AVI unity ac_new', units='density', nodata_fill=0)>50, ",
                           med.coef$vegcPine,
                           ",if(indicator(name='Agriculture Pasture Unityb', units='density', nodata_fill=0)>50, ",
                           med.coef$RoughP,
                           ",if(indicator(name='Rural Settlement Unityb', units='density', nodata_fill=0)>50, ",
                           med.coef$vegcRural,
                           ",if(indicator(name='Shrubland Unityb', units='density', nodata_fill=0)>50, ",
                           med.coef$vegcShrub,
                           ",if(indicator(name='White Spruce AVI unity ac_new', units='density', nodata_fill=0)>50, ",
                           med.coef$vegcSpruce,
                           ",if(indicator(name='Wetlands Swamp', units='density', nodata_fill=0)>50, ",
                           med.coef$vegcSwamp,
                           ",if(indicator(name='Urban Undifferentiated Unityb', units='density', nodata_fill=0)>50,",
                           med.coef$vegcUrban,
                           ",",med.coef$vegcTameP,")))))))))))))))))+",
                           med.coef$wtAge,
                           "*indicator(name='MeanForestAgeBAMABMIbirdmodels v3 ac_new', units='density', nodata_fill=0)+",
                           med.coef$wtAge2,
                           "*((indicator(name='MeanForestAgeBAMABMIbirdmodels v3 ac_new', units='density', nodata_fill=0))**2)+",
                           med.coef$wtAge05,
                           "*sqrt(indicator(name='MeanForestAgeBAMABMIbirdmodels v3 ac_new', units='density', nodata_fill=0))+",
                           med.coef$ROAD,
                           "*(indicator(name='Major Road Unityb', units='density', nodata_fill=0)+indicator(name='Minor Road Unityb', units='density', nodata_fill=0))/100+",
                           med.coef$mWell,
                           "*(indicator(name='PetroWell Gas Unityb', units='density', nodata_fill=0)+indicator(name='PetroWell Oil Unityb', units='density', nodata_fill=0)+indicator(name='PetroWell Other Unityb', units='density', nodata_fill=0)+indicator(name='PetroWell Water Unityb', units='density', use_static=True, static_time=2010, nodata_fill=0))/100+",
                           med.coef$mSeism,
                           "*indicator(name='Seismic Lines Unityb', units='density', nodata_fill=0)/100+",
                           med.coef$mEnSft,
                           "*indicator(name='Pipelines Unityb', units='density', nodata_fill=0)/100+",
                           med.coef$xY,
                           "*indicator(name='xLatitude ac_new', units='density', scen='historic - empirical or loaded from outside data', use_static=True, static_time=2010, nodata_fill=0)+",
                           med.coef$xX,
                           "*indicator(name='xLongitude ac_new', units='density', scen='historic - empirical or loaded from outside data', use_static=True, static_time=2010, nodata_fill=0)+",
                           med.coef$xY2,
                           "*((indicator(name='xLatitude ac_new', units='density', scen='historic - empirical or loaded from outside data', use_static=True, static_time=2010, nodata_fill=0))**2)+",
                           med.coef$xX2,
                           "*((indicator(name='xLongitude ac_new', units='density', scen='historic - empirical or loaded from outside data', use_static=True, static_time=2010, nodata_fill=0))**2)+",
                           med.coef$xX.xY,
                           "*indicator(name='xLatitude ac_new', units='density', scen='historic - empirical or loaded from outside data', use_static=True, static_time=2010, nodata_fill=0)*indicator(name='xLongitude ac_new', units='density', scen='historic - empirical or loaded from outside data', use_static=True, static_time=2010, nodata_fill=0)+",
                           med.coef$pWater_KM,
                           "*indicator(name='Water Lentic 1000m', units='density', nodata_fill=0)/100+",
                           med.coef$pWater2_KM,
                           "*((indicator(name='Water Lentic 1000m', units='density', nodata_fill=0)/100)**2)+",
                           med.coef$Cult_KM,
                           "*indicator(name='Total Agriculture 1000m', units='density', nodata_fill=0)/100+",
                           med.coef$Noncult_KM,
                           "*indicator(name='Nonagricultural Footprint Alpac 1000m', units='density', nodata_fill=0)/100+",
                           med.coef$Noncult2_KM,
                           "*((indicator(name='Nonagricultural Footprint Alpac 1000m', units='density', nodata_fill=0)/100)**2)+",
                           med.coef$Succ_KM,
                           "*indicator(name='Seismic Pipeline Cutblock AVI 1000m', units='density', nodata_fill=0)/100+",
                           med.coef$Alien_KM,
                           "*indicator(name='Alienating land use 1000m', units='density', nodata_fill=0)/100+",
                           med.coef$Alien2_KM,
                           "*((indicator(name='Alienating land use 1000m', units='density', nodata_fill=0)/100)**2) +",
                           med.coef$Succ2_KM,
                           "*((indicator(name='Seismic Pipeline Cutblock AVI 1000m', units='density', nodata_fill=0)/100)**2) +",
                           med.coef$xMAT.xPET,
                           "*indicator(name='xPotential Evapotranspiration ac_new', units='density', scen='historic - empirical or loaded from outside data', use_static=True, static_time=2010, nodata_fill=0)*indicator(name='xMean Annual Precipitation ac_new', units='density', scen='historic - empirical or loaded from outside data', use_static=True, static_time=2010, nodata_fill=0)+",
                           med.coef$xAHM.xMAT,
                           "*indicator(name='xMean Annual Temperature ac_new', units='density', scen='historic - empirical or loaded from outside data', use_static=True, static_time=2010, nodata_fill=0)*indicator(name='xAnnual Heat Moisture Index ac_new', units='density', scen='historic - empirical or loaded from outside data', use_static=True, static_time=2010, nodata_fill=0)+",
                           med.coef$xPET,
                           "*indicator(name='xPotential Evapotranspiration ac_new', units='density', scen='historic - empirical or loaded from outside data', use_static=True, static_time=2010, nodata_fill=0)+",
                           med.coef$xMAT,
                           "*indicator(name='xMean Annual Temperature ac_new', units='density', scen='historic - empirical or loaded from outside data', use_static=True, static_time=2010, nodata_fill=0)+",
                           med.coef$xAHM,
                           "*indicator(name='xAnnual Heat Moisture Index ac_new', units='density', scen='historic - empirical or loaded from outside data', use_static=True, static_time=2010, nodata_fill=0)+",
                           med.coef$xFFP,
                           "*indicator(name='xFrost Free Period ac_new', units='density', scen='historic - empirical or loaded from outside data', use_static=True, static_time=2010, nodata_fill=0)+",
                           med.coef$xMAP,
                           "*indicator(name='xMean Annual Precipitation ac_new', units='density', scen='historic - empirical or loaded from outside data', use_static=True, static_time=2010, nodata_fill=0)+",
                           med.coef$xFFP.xMAP,
                           "*indicator(name='xFrost Free Period ac_new', units='density', scen='historic - empirical or loaded from outside data', use_static=True, static_time=2010, nodata_fill=0)*indicator(name='xMean Annual Precipitation ac_new', units='density', scen='historic - empirical or loaded from outside data', use_static=True, static_time=2010, nodata_fill=0)+",
                           med.coef$xMCMT,
                           "*indicator(name='xMean Coldest Month Temperature ac_new', units='density', use_static=True, static_time=2010, nodata_fill=0)+",
                           med.coef$xMWMT,
                           "*indicator(name='xMean Warmest Month Temperature ac_new', units='density', use_static=True, static_time=2010)+",
                           "if((if(indicator(name='Mixed Origin AVI', units='density', nodata_fill=0)==3,indicator(name='Mixed AVI unity ac_new', units='density', nodata_fill=0),0)+if(indicator(name='Deciduous Origin AVI', units='density', nodata_fill=0)==3,indicator(name='Deciduous AVI unity ac_new', units='density', nodata_fill=0),0)+if(indicator(name='White Spruce Origin AVI', units='density', nodata_fill=0)==3,indicator(name='White Spruce AVI unity ac_new', units='density', nodata_fill=0),0)+if(indicator(name='Pine Origin AVI', units='density', nodata_fill=0)==3,indicator(name='Pine AVI unity ac_new', units='density', nodata_fill=0),0))>50,1-(indicator(name='MeanForestAgeBAMABMIbirdmodels v3 ac_new', units='density', nodata_fill=0)*200/50),0)+",
                           "if((indicator(name='Black Spruce AVI unity ac_new', units='density', nodata_fill=0))>50,",
                           med.coef$isBSLarch.wtAge,
                           "*indicator(name='MeanForestAgeBAMABMIbirdmodels v3 ac_new', units='density', nodata_fill=0)+",
                           med.coef$isBSLarch.wtAge2,
                           "*((indicator(name='MeanForestAgeBAMABMIbirdmodels v3 ac_new', units='density', nodata_fill=0))**2)+",
                           med.coef$isBSLarch.wtAge05,
                           "*sqrt(indicator(name='MeanForestAgeBAMABMIbirdmodels v3 ac_new', units='density', nodata_fill=0)),",
                           "if(indicator(name='White Spruce AVI unity ac_new', units='density', nodata_fill=0)>50,",
                           med.coef$isWSpruce.wtAge,
                           "*indicator(name='MeanForestAgeBAMABMIbirdmodels v3 ac_new', units='density', nodata_fill=0)+",
                           med.coef$isWSpruce.wtAge2,
                           "*((indicator(name='MeanForestAgeBAMABMIbirdmodels v3 ac_new', units='density', nodata_fill=0))**2)+",
                           med.coef$isWSpruce.wtAge05,
                           "*sqrt(indicator(name='MeanForestAgeBAMABMIbirdmodels v3 ac_new', units='density', nodata_fill=0)),",
                           "if(indicator(name='Pine AVI unity ac_new', units='density', nodata_fill=0)>50,",
                           med.coef$isPine.wtAge,
                           "*indicator(name='MeanForestAgeBAMABMIbirdmodels v3 ac_new', units='density', nodata_fill=0)+",
                           med.coef$isPine.wtAge2,
                           "*((indicator(name='MeanForestAgeBAMABMIbirdmodels v3 ac_new', units='density', nodata_fill=0))**2)+",
                           med.coef$isPine.wtAge05,
                           "*sqrt(indicator(name='MeanForestAgeBAMABMIbirdmodels v3 ac_new', units='density', nodata_fill=0)),",
                           "if(indicator(name='Mixed AVI unity ac_new', units='density', nodata_fill=0)>50,",
                           med.coef$isMix.wtAge,
                           "*indicator(name='MeanForestAgeBAMABMIbirdmodels v3 ac_new', units='density', nodata_fill=0)+",
                           med.coef$isMix.wtAge2,
                           "*((indicator(name='MeanForestAgeBAMABMIbirdmodels v3 ac_new', units='density', nodata_fill=0))**2)+",
                           med.coef$isMix.wtAge05,
                           "*sqrt(indicator(name='MeanForestAgeBAMABMIbirdmodels v3 ac_new', units='density', nodata_fill=0)),",
                           "if((indicator(name='White Spruce AVI unity ac_new', units='density', nodata_fill=0)+indicator(name='Pine AVI unity ac_new', units='density', nodata_fill=0))>50,+",
                           med.coef$isUpCon.wtAge,
                           "*indicator(name='MeanForestAgeBAMABMIbirdmodels v3 ac_new', units='density', nodata_fill=0)+",
                           med.coef$isUpCon.wtAge2,
                           "*((indicator(name='MeanForestAgeBAMABMIbirdmodels v3 ac_new', units='density', nodata_fill=0))**2)+",
                           med.coef$isUpCon.wtAge05,
                           "*sqrt(indicator(name='MeanForestAgeBAMABMIbirdmodels v3 ac_new', units='density', nodata_fill=0)),",
                           "if((indicator(name='White Spruce AVI unity ac_new', units='density', nodata_fill=0)+indicator(name='Pine AVI unity ac_new', units='density', nodata_fill=0)+indicator(name='Black Spruce AVI unity ac_new', units='density', nodata_fill=0)+indicator(name='Larch AVI unity ac_new', units='density', nodata_fill=0))>50,+",
                           med.coef$isCon.wtAge,
                           "*indicator(name='MeanForestAgeBAMABMIbirdmodels v3 ac_new', units='density', nodata_fill=0)+",
                           med.coef$isCon.wtAge2,
                           "*((indicator(name='MeanForestAgeBAMABMIbirdmodels v3 ac_new', units='density', nodata_fill=0))**2),0))))))+",
                           med.coef$Lin_KM,
                           "*indicator(name='Linear footprint 1000m', units='density', nodata_fill=0)/100+",
                           med.coef$Nonlin_KM,
                           "*indicator(name='Nonlinear footprint AVI 1000m', units='density', nodata_fill=0)/100+",
                           med.coef$Nonlin2_KM,
                           "*((indicator(name='Nonlinear footprint AVI 1000m', units='density',nodata_fill=0)/100)**2)+",
                           med.coef$SSH_KM,
                           "*indicator(name='",SPP," preferred habitat 1000m', units='density', nodata_fill=0)/100+",
                           med.coef$SSH05_KM,
                           "*sqrt(indicator(name='OVEN preferred habitat 1000m', units='density',nodata_fill=0)/100)+",
                           med.coef$THF_KM,
                           "*((indicator(name='Linear footprint 1000m', units='density', nodata_fill=0)+indicator(name='Nonlinear footprint AVI 1000m', units='density',nodata_fill=0))/100)+",
                           med.coef$THF2_KM,
                           "*(((indicator(name='Linear footprint 1000m', units='density', nodata_fill=0)+indicator(name='Nonlinear footprint AVI 1000m', units='density',nodata_fill=0))/100)**2))"))
  capture.output(spp.script, file=paste0("species indicators/",SPP,"indicator.mediancoefvals.txt"))
}#Note that return carriages (/n) should be removed from the indicators before they are used in ALCES Advanced Calculator